// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlhnevapvfbcscmkqoxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsaG5ldmFwdmZiY3NjbWtxb3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDQ2MDEsImV4cCI6MjA2NzIyMDYwMX0.A96DaHbQtJ_9ngvcISqUpoy4z0gsazKjET7fWwq-RgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});